export const AUTHENTICATION = "AUTHENTICATION"
export const LOGOUT = "LOGOUT"
export const GETPRODUCTS = "FARMER-GET-PRODUCTS"
export const UPDATEPRODUCT = "UPDATE-PRODUCT"
export const CREATEPRODUCT = "CREATE-PRODUCT"
export const UPDATEUSER = "UPDATE-USER"
export const GETUSER = "GET-USER"
export const GETPRODUCTSFORCUSTOMERS = "GET-PRODUCTS-FOR-CUSTOMERS"
export const ADDUSERADDRESS = "ADD-USER-ADDRESS"

export const GETCART = "GETCART";
export const SAVECART = "SAVECART";
export const DELETECARTITEM = "DELETE-CART-ITEM";
export const UPDATECART = "UPDATE-CART" 
export const ADDITEMTOCART = "ADD-ITEM-TO-CART"
export const CLEARCART = "CLEAR-CART"

export const GETORDERBYID = "GET-ORDER-BY-ID";
export const FETCHFARMERORDER = "FETCH-FARMER-ORDER";
export const FETCHCUSTOMERORDER = "FETCH-CUSTOMER-ORDER";

// --- Admin ---
export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";
export const ADMIN_FETCH_USERS = "ADMIN_FETCH_USERS";
export const ADMIN_FETCH_USER = "ADMIN_FETCH_USER";
export const ADMIN_UPDATE_USER = "ADMIN_UPDATE_USER";
export const ADMIN_DELETE_USER = "ADMIN_DELETE_USER";

export const ADMIN_FETCH_PRODUCTS = "ADMIN_FETCH_PRODUCTS";
export const ADMIN_CREATE_PRODUCT = "ADMIN_CREATE_PRODUCT";
export const ADMIN_UPDATE_PRODUCT = "ADMIN_UPDATE_PRODUCT";
export const ADMIN_DELETE_PRODUCT = "ADMIN_DELETE_PRODUCT";

export const ADMIN_FETCH_ORDERS = "ADMIN_FETCH_ORDERS";
export const ADMIN_FETCH_ORDER = "ADMIN_FETCH_ORDER";
export const ADMIN_UPDATE_ORDER = "ADMIN_UPDATE_ORDER";
export const ADMIN_DELETE_ORDER = "ADMIN_DELETE_ORDER";

export const ADMIN_FETCH_CATEGORIES = "ADMIN_FETCH_CATEGORIES";
export const ADMIN_CREATE_CATEGORY = "ADMIN_CREATE_CATEGORY";
export const ADMIN_UPDATE_CATEGORY = "ADMIN_UPDATE_CATEGORY";
export const ADMIN_DELETE_CATEGORY = "ADMIN_DELETE_CATEGORY";

export const ADMIN_FETCH_REGIONS = "ADMIN_FETCH_REGIONS";
export const ADMIN_CREATE_REGION = "ADMIN_CREATE_REGION";
export const ADMIN_UPDATE_REGION = "ADMIN_UPDATE_REGION";
export const ADMIN_DELETE_REGION = "ADMIN_DELETE_REGION";

export const ADMIN_FETCH_DASHBOARD_KPIS = "ADMIN_FETCH_DASHBOARD_KPIS";