export const AUTHENTICATION = "AUTHENTICATION"
export const LOGOUT = "LOGOUT"
export const GETPRODUCTS="FARMER-GET-PRODUCTS"
export const UPDATEPRODUCT="UPDATE-PRODUCT"
export const CREATEPRODUCT="CREATE-PRODUCT"
export const UPDATEUSER="UPDATE-USER"
export const GETUSER="GET-USER"
export const GETPRODUCTSFORCUSTOMERS="GET-PRODUCTS-FOR-CUSTOMERS"
export const ADDUSERADDRESS="ADD-USER-ADDRESS"

export const GETCART = "GETCART";
export const SAVECART = "SAVECART";
export const DELETECARTITEM = "DELETE-CART-ITEM";
export const UPDATECART="UPDATE-CART" 
export const ADDITEMTOCART="ADD-ITEM-TO-CART"
export const CLEARCART="CLEAR-CART"

export const GETORDERBYID="GET-ORDER-BY-ID";
export const FETCHFARMERORDER="FETCH-FARMER-ORDER";
export const FETCHCUSTOMERORDER="FETCH-CUSTOMER-ORDER";